version: '3.7'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.7
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  mongo:
    image: mongo
    container_name: mongodb
    command: --serviceExecutor adaptive
    ports:
      - 27017:27017
      - 28017:28017
